import { describe, expect, test } from 'bun:test'
import { readdir, readFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { parse } from 'yaml'
import {
  emitRustModuleIndex,
  emitTypeScriptModelIndex,
  extractModelGroups,
  flattenRequiredHeaderGuards,
  mergeRustModels,
  mergeTypeScriptModels,
} from './claw-api'

interface OpenApiOperation {
  operationId?: string
  parameters?: Array<{
    in?: string
    name?: string
  }>
}

interface OpenApiDocument {
  openapi?: string
  paths?: Record<string, Record<string, OpenApiOperation> & { $ref?: string }>
  components?: {
    schemas?: Record<string, unknown>
  }
}

const contractPath = join(
  import.meta.dir,
  '../../contracts/claw-api/openapi.yaml',
)
const contractDirectory = dirname(contractPath)

const expectedPaths = [
  '/system/health',
  '/system/shutdown',
  '/api/v1/system',
  '/api/v1/settings/telemetry',
  '/api/v1/recordings/events',
  '/api/v1/sessions',
  '/api/v1/sessions/{sessionId}',
  '/api/v1/sessions/{sessionId}/cancel',
  '/api/v1/sessions/{sessionId}/recording',
  '/api/v1/sessions/{sessionId}/recording/events',
  '/api/v1/sessions/{sessionId}/browser-tabs/{browserTabId}/preview',
  '/api/v1/dispatches/{dispatchId}/screenshot',
  '/api/v1/connections',
  '/api/v1/connections/{harness}',
]

describe('BrowserClaw OpenAPI contract', () => {
  test('defines only the approved canonical surface with unique operation IDs', async () => {
    const source = await readFile(contractPath, 'utf8')
    const document = parse(source) as OpenApiDocument

    expect(document.openapi).toBe('3.0.3')
    expect(Object.keys(document.paths ?? {}).sort()).toEqual(
      expectedPaths.toSorted(),
    )

    const pathItems = await Promise.all(
      Object.values(document.paths ?? {}).map(async (path) => {
        if (!path.$ref) return path
        return parse(
          await readFile(resolve(contractDirectory, path.$ref), 'utf8'),
        ) as Record<string, OpenApiOperation>
      }),
    )
    const operations = pathItems.flatMap((path) =>
      Object.entries(path).filter(([method]) =>
        ['get', 'put', 'post', 'delete', 'patch'].includes(method),
      ),
    )
    const operationIds = operations.map(
      ([, operation]) => operation.operationId,
    )
    expect(operationIds.every(Boolean)).toBe(true)
    expect(new Set(operationIds).size).toBe(operationIds.length)
  })

  test('does not expose legacy execution identities', async () => {
    const sources = await Promise.all(
      (await yamlFiles(contractDirectory)).map((path) =>
        readFile(path, 'utf8'),
      ),
    )
    expect(sources.join('\n')).not.toMatch(/\b(?:agentId|taskId|runId)\b/)
  })
})

describe('flattenRequiredHeaderGuards', () => {
  test('flattens required header assignments and preserves optional guards', () => {
    const generated = `        if (requestParameters['required'] == null) {
            throw new Error('required');
        }

        if (requestParameters['required'] != null) {
            headerParameters['Required'] = String(requestParameters['required']);
        }

        if (requestParameters['optional'] != null) {
            headerParameters['Optional'] = String(requestParameters['optional']);
        }
`

    expect(
      flattenRequiredHeaderGuards(generated),
    ).toBe(`        if (requestParameters['required'] == null) {
            throw new Error('required');
        }

        headerParameters['Required'] = String(requestParameters['required']);

        if (requestParameters['optional'] != null) {
            headerParameters['Optional'] = String(requestParameters['optional']);
        }
`)
  })
})

describe('extractModelGroups', () => {
  test('derives model groups from schema ref files', () => {
    const source = `components:
  schemas:
    ApiError:
      $ref: ./schemas/common.yaml#/ApiError
    SessionDetail:
      $ref: ./schemas/sessions.yaml#/SessionDetail
`

    expect(extractModelGroups(source, ['SessionDetail', 'ApiError'])).toEqual({
      ApiError: 'common',
      SessionDetail: 'sessions',
    })
  })

  test('rejects schema refs outside the group-file convention', () => {
    const source = `components:
  schemas:
    ApiError:
      $ref: ./shared.yaml#/ApiError
`

    expect(() => extractModelGroups(source, ['ApiError'])).toThrow(
      'ApiError schema ref must match ./schemas/<group>.yaml#/<model>',
    )
  })

  test('rejects contract and generated model drift in either direction', () => {
    const source = `components:
  schemas:
    ApiError:
      $ref: ./schemas/common.yaml#/ApiError
`

    expect(() => extractModelGroups(source, ['Unexpected'])).toThrow(
      'Generated model Unexpected has no schema group',
    )
    expect(() => extractModelGroups(source, [])).toThrow(
      'OpenAPI schema ApiError has no generated model',
    )
  })
})

describe('mergeRustModels', () => {
  const header = `/*
 * BrowserClaw API
 *
 * Generated by: https://openapi-generator.tech
 */`

  test('deduplicates the header and imports and sorts member bodies', () => {
    expect(
      mergeRustModels({
        Zebra: `${header}

use serde::{Deserialize, Serialize};
use crate::models;

pub struct Zebra;
`,
        Alpha: `${header}

use crate::models;
use serde::{Deserialize, Serialize};

pub struct Alpha;
`,
      }),
    ).toBe(`${header}

use crate::models;
use serde::{Deserialize, Serialize};

pub struct Alpha;

pub struct Zebra;
`)
  })

  test('rejects differing generated headers', () => {
    expect(() =>
      mergeRustModels({
        Alpha: `${header}\n\nuse crate::models;\n\npub struct Alpha;\n`,
        Beta: `/* changed */\n\nuse crate::models;\n\npub struct Beta;\n`,
      }),
    ).toThrow('Rust model Beta has a different generated header')
  })
})

describe('emitRustModuleIndex', () => {
  test('declares sorted group modules with flat re-exports', () => {
    expect(emitRustModuleIndex(['system', 'common', 'sessions'])).toBe(
      `pub mod common;
pub use self::common::*;
pub mod sessions;
pub use self::sessions::*;
pub mod system;
pub use self::system::*;
`,
    )
  })
})

describe('mergeTypeScriptModels', () => {
  const preamble = `/* tslint:disable */
/* eslint-disable */
/** Generated model. */`
  const modelGroups = {
    Alpha: 'sessions',
    Beta: 'sessions',
    Common: 'common',
    Zebra: 'connections',
  }

  test('rewrites and merges imports, then sorts member bodies', () => {
    expect(
      mergeTypeScriptModels(
        {
          Beta: `${preamble}

import { mapValues } from '../runtime.js';
import type { Alpha } from './Alpha.js';
import type { Zebra } from './Zebra.js';
import {
    ZebraFromJSON,
    ZebraToJSON,
} from './Zebra.js';

export interface Beta {}
`,
          Alpha: `${preamble}

import { mapValues } from '../runtime.js';
import type { Common } from './Common.js';
import { CommonFromJSON } from './Common.js';
import type { Zebra } from './Zebra.js';
import { ZebraFromJSON } from './Zebra.js';

export interface Alpha {}
`,
        },
        modelGroups,
      ),
    ).toBe(`${preamble}

import { mapValues } from '../runtime.js';
import type { Common } from './common.js';
import { CommonFromJSON } from './common.js';
import type { Zebra } from './connections.js';
import {
    ZebraFromJSON,
    ZebraToJSON,
} from './connections.js';

export interface Alpha {}

export interface Beta {}
`)
  })

  test('rejects imports outside the generated model shapes', () => {
    expect(() =>
      mergeTypeScriptModels(
        {
          Alpha: `${preamble}

import defaultValue from './Common.js';

export interface Alpha {}
`,
        },
        modelGroups,
      ),
    ).toThrow('TypeScript model Alpha has an unrecognized import')
  })
})

describe('emitTypeScriptModelIndex', () => {
  test('exports one sorted module per group', () => {
    expect(emitTypeScriptModelIndex(['system', 'common', 'sessions'])).toBe(
      `/* tslint:disable */
/* eslint-disable */
export * from './common.js';
export * from './sessions.js';
export * from './system.js';
`,
    )
  })
})

async function yamlFiles(directory: string): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map((entry) => {
      const path = join(directory, entry.name)
      if (entry.isDirectory()) return yamlFiles(path)
      return Promise.resolve(entry.name.endsWith('.yaml') ? [path] : [])
    }),
  )
  return nested.flat()
}
